"use client"

import React, { useState } from 'react';

interface FaqData {
  question: string;
  answer: string;
}

const faqData: FaqData[] = [
  {
    question: "How does gTahidi AI ensure the accuracy of lesson plans and content?",
    answer: "gTahidi AI is built on advanced machine learning models and has been trained with a vast amount of educational content. We continually update and refine our algorithms to ensure educators receive accurate and reliable lesson materials. Additionally, educators have the option to customize and adjust content as per their needs. "
  },
  {
    question: "Is it necessary to credit gTahidi AI when using the generated content?",
    answer: "While the content generated by gTahidi AI is original, it's always a good practice to mention any tools or resources you use. However, it isn't mandatory to cite gTahidi AI unless specifically mentioned in your terms of service. "
  },
  {
    question: "Who is the target audience for gTahidi AI? ",
    answer: "gTahidi AI is designed specifically for educators, tutors, and teachers. It assists in streamlining the lesson planning process, generating quizzes, and producing notes to enhance the teaching experience.  "
  },
  {
    question: "How does gTahidi AI differ from ChatGPT? ",
    answer: "While both utilize advanced AI models, gTahidi AI is  specifically tailored for educational purposes, assisting educators in lesson planning and content generation. ChatGPT, on the other hand, is more generalized and is designed for versatile conversational interactions.  "
  },
  {
    question: "Do you have special packages for educational institutions? ",
    answer: "Absolutely! We offer customized plans suited for schools, colleges, and other educational institutions. Please contact our sales team for more details.  "
  },
  {
    question: "How is the billing process structured?  ",
    answer: "Billing is based on the subscription plan you choose. You'll receive detailed invoices for every transaction, and various payment methods are accepted.  "
  },
  {
    question: "Will my gTahidi AI subscription renew automatically? ",
    answer: "Yes, subscriptions are set to auto-renew to ensure uninterrupted service. However, you can change this setting in your account preferences.  "
  },
  {
    question: "What's the policy on subscription cancellations?  ",
    answer: "We offer a straightforward cancellation policy. You can cancel anytime from your account settings. For detailed terms and conditions, refer to our cancellation policy page. "
  },
  {
    question: "How frequently does gTahidi AI roll out new features?  ",
    answer: "We're continually improving! We roll out updates and new features based on user feedback and technological advancements. Stay tuned to our update logs for the latest additions. "
  },
  {
    question: "Which devices support gTahidi AI?   ",
    answer: "gTahidi AI is a cloud-based platform, making it accessible from any device with a web browser. Whether you're using a computer, tablet, or smartphone, gTahidi AI is ready for you. "
  },
  {
    question: "Is there a specific app to download for gTahidi AI?  ",
    answer: "Currently, gTahidi AI is web-based, so there's no need to download a separate app. You can access it directly through your browser for seamless experience across devices. "
  },

];

function Faqs() {
  const [openFaq, setOpenFaq] = useState<number | null>(null);

  const toggleFaq = (index: number) => {
    setOpenFaq(openFaq === index ? null : index);
  };

  return (
    <div>
      <section className="bg-white dark:bg-gray-900">
        <div className="container max-w-4xl px-6 py-10 mx-auto">
          <h1 className="text-2xl font-semibold text-center text-gtahidiPink lg:text-3xl dark:text-white">
            Frequently asked questions
          </h1>
          <div className="mt-12 space-y-8">
            {faqData.map(({ question, answer }, index) => (
              <div key={index} className="border-2 border-gray-100 rounded-lg dark:border-gray-700">
                <button onClick={() => toggleFaq(index)} className="flex items-center justify-between w-full p-8">
                  <h1 className="font-semibold text-gray-700 dark:text-white">{question}</h1>
                  <span className="text-white bg-gtahidiPink rounded-full">
                              <svg xmlns="http://www.w3.org/2000/svg" className="w-6 h-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                  <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6" />
                              </svg>
                          </span>
                </button>
                {openFaq === index && (
                  <p className="p-8 text-sm text-gray-500 dark:text-gray-300">{answer}</p>
                )}
              </div>
            ))}
          </div>
        </div>
      </section>
    </div>
  );
}

export default Faqs;
