name: ci

on:
  push:
    branches:
      - "main"

jobs:
  deploy_to_azure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Azure App Service
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up Azure CLI
        uses: azure/CLI@v1

      - name: Deploy Container to Azure App Service
        run: |
          # Use Azure CLI or ARM templates to deploy the container to Azure App Service

        app-name: 'gtahidi'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1d485eb621d640fa98c4e00b3c0bc132 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_a31f05f873264d66a619299d812e294d }}/dante254/clockbox:${{ github.sha }}'
